name: Run on mob push

on:
  push:
    branches:
      - mob

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: github-actions

      - name: Debug - Show current directory
        run: |
          pwd
          echo "Contents of the current directory:"
          ls -al
